# Generated by Django 5.2.18 on 2026-10-08 17:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "mode",
                    models.CharField(
                        choices=[("classic", "Clássica"), ("enhanced", "Aprimorada")],
                        default="classic",
                        max_length=10,
                        verbose_name="modo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "esteira",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tarefa")),
                (
                    "gravity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="gravidade",
                    ),
                ),
                (
                    "urgency",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="urgência",
                    ),
                ),
                (
                    "trend",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="tendência",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("content", "Conteúdo"),
                            ("assessment", "Avaliação"),
                            ("admin", "Administrativo"),
                            ("project", "Projeto"),
                            ("personal", "Pessoal"),
                        ],
                        default="content",
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="prazo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("running", "Em execução"),
                            ("paused", "Pausada"),
                            ("blocked", "Bloqueada"),
                            ("done", "Concluída"),
                            ("discarded", "Descartada"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="boards.board",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarefa",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("owner", "mode"), name="one_board_per_mode_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("board",),
                name="one_running_task_per_board",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gravity__range", (1, 5)),
                    ("urgency__range", (1, 5)),
                    ("trend__range", (1, 5)),
                ),
                name="gut_ratings_between_1_and_5",
            ),
        ),
    ]
