# Generated by Django 5.2.18 on 2026-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="queue_limit",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Só vale para a esteira aprimorada.",
                verbose_name="teto de tarefas abertas",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "até 15 min"),
                    ("s", "até 1 hora"),
                    ("m", "até meio período"),
                    ("l", "até um dia"),
                    ("xl", "mais de um dia"),
                ],
                max_length=2,
                verbose_name="esforço real",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "até 15 min"),
                    ("s", "até 1 hora"),
                    ("m", "até meio período"),
                    ("l", "até um dia"),
                    ("xl", "mais de um dia"),
                ],
                max_length=2,
                verbose_name="esforço",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="interruptions",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="interrupções"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority_verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("right", "Veio na hora certa"),
                    ("late", "Deveria ter vindo antes"),
                    ("early", "Poderia ter esperado"),
                ],
                max_length=5,
                verbose_name="a prioridade estava certa?",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="running_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status_reason",
            field=models.CharField(blank=True, max_length=200, verbose_name="motivo"),
        ),
        migrations.AddField(
            model_name="task",
            name="worked_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
